:py:mod:`aop.tools`
===================

.. py:module:: aop.tools

.. autoapi-nested-parse::

   :Author: AmÃ©lie Solveigh Hohe
   :Contact: nina.tolfersheimer@posteo.de

   This module contains auxiliary classes and functions for the aop package.



Module Contents
---------------

.. py:exception:: AolFileAlreadyExistsError(filepath: str, session_id: str)

   Bases: :py:obj:`Exception`

   An error raised upon trying to initialize an .aol file that already exists.


.. py:exception:: AolNotFoundError(session_id: str)

   Bases: :py:obj:`Exception`

   An error raised upon trying to load an .aol file that doesn't exist.


.. py:exception:: AopFileAlreadyExistsError(filepath: str, session_id: str)

   Bases: :py:obj:`Exception`

   An error raised upon trying to initialize an .aop file that already exists.


.. py:exception:: InvalidTimeStringError(invalid_string: str)

   Bases: :py:obj:`Exception`

   An error raised upon providing a string to current_jd's time argument that is not interpretable as a time.


.. py:exception:: SessionIDDoesntExistOnFilepathError(invalid_id: str)

   Bases: :py:obj:`Exception`

   An error raised when a specified session ID could not be found on the provided filepath.


.. py:exception:: SessionStateError(event: str, state: str)

   Bases: :py:obj:`Exception`

   An error raised when the current session parameters don't allow for the requested operation.

   .. py:method:: __str__() -> str

      The default custom error message of SessionStateError

      :return: default custom error message
      :rtype: ``str``



.. py:exception:: NotInterruptableError

   Bases: :py:obj:`SessionStateError`

   An error raised when trying to interrupt a session that is not currently 'running'.

   Inherits from SessionStateError, uses "interrupt session" as impossible operation
   and "not running" as problematic session state.


.. py:exception:: NotResumableError

   Bases: :py:obj:`SessionStateError`

   An error raised when trying to resume a session that is not currently 'running'.

   Inherits from SessionStateError, uses "resume session" as impossible operation
   and "not running" as problematic session state.


.. py:exception:: NotAbortableError

   Bases: :py:obj:`SessionStateError`

   An error raised when trying to abort a session that is not currently 'running'.

   Inherits from SessionStateError, uses "abort session" as impossible operation
   and "not running" as problematic session state.


.. py:exception:: NotEndableError

   Bases: :py:obj:`SessionStateError`

   An error raised when trying to end a session that is not currently 'running'.

   Inherits from SessionStateError, uses "end session" as impossible operation
   and "not running" as problematic session state.


.. py:exception:: AlreadyInterruptedError

   Bases: :py:obj:`SessionStateError`

   An error raised when trying to interrupt a session that is already 'interrupted'.

   Inherits from SessionStateError, uses "interrupt session" as impossible operation
   and "interrupted" as problematic session state.


.. py:exception:: NotInterruptedError

   Bases: :py:obj:`SessionStateError`

   An error raised when trying to resume a session that is not currently 'interrupted'.

   Inherits from SessionStateError, uses "resume session" as impossible operation
   and "not interrupted" as problematic session state.


.. py:exception:: SessionNotStartedError(illegal_operation: str)

   Bases: :py:obj:`Exception`

   An error raised when trying to perform a session operation before the session has been started.

   .. py:method:: __repr__() -> str

      Custom error message.

      :return: custom error message
      :rtype: ``str``



